2025-10-11 17:32:43,924 [INFO] App started
2025-10-11 17:32:43,924 [WARNING] This is a warning
2025-10-11 17:32:43,924 [ERROR] This is an error message
2025-10-11 17:32:43,924 [ERROR] An exception occurred
Traceback (most recent call last):
  File "e:\ai_learning\day02_basics\day05_logging.py", line 15, in <module>
    x = 10 / 0
        ~~~^~~
ZeroDivisionError: division by zero
2025-10-11 17:32:43,930 [INFO] App finished
